### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by TheBricktop** [MyEvolution/OnePiece#1]
Can you actually put on MIT license on a code using MILD ? I think its GPL licensed.

**Comment by MyEvolution** [comment]
I haven't noticed it, thanks for your reminder!

**Comment by MyEvolution** [comment]
I will ask the author to make sure that if i can use it under MIT license.

**Comment by TheBricktop** [comment]
Sorry for nitpicking im just currently on a quest for working slam solution for mobile devices and im hoping for some mit licensed base for development. Thats why im thorought with that.

**Comment by MyEvolution** [comment]
> Sorry for nitpicking im just currently on a quest for working slam solution for mobile devices and im hoping for some mit licensed base for development. Thats why im thorought with that.

Hey, i have asked the author for the license, this is what he said:

> MILD is released for acdemic usages only. For a closed-source version of MILD for commercial purposes, please contact the authors.
> If you use MILD in an academic work, please cite the most relevant publication associated by visiting:
> https://github.com/lhanaf/MILD

**Comment by MyEvolution** [comment]
I think https://github.com/intel-isl/Open3D will be a better solution for you.
