### ISSUE TITLE
revise CMakelists.txt to solve warning and errors

### ISSUE THREAD

**Issue by renhaofan** [MyEvolution/OnePiece#2]
Error: CMake Error: The source directory "./example/CMakeFiles/CMakeTmp" does not exist.

CMakeLists.txt:4
modify `set (CMAKE_BINARY_DIR "./example")` 
to `set(CMAKE_BINARY_DIR  "${CMAKE_CURRENT_SOURCE_DIR}/example")`

Warning: [issues](https://github.com/ilpincy/argos3/issues/88)
add 
```
if (POLICY CMP0072)
  set(OpenGL_GL_PREFERENCE LEGACY)
endif()

```
in CMakeLists.txt

**Comment by MyEvolution** [comment]
Thanks!
